# Generated by Django 5.0.1 on 2025-01-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
