# Generated by Django 5.0.1 on 2025-01-27 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=200)),
                ('rated', models.CharField(max_length=40)),
                ('runtime', models.CharField(max_length=40)),
                ('Genre', models.CharField(max_length=50)),
                ('Director', models.CharField(max_length=60)),
                ('Actors', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=50)),
                ('plot', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
